MW_SYS_VER=v24.03M01

OS_MODULE:=freertos
OS_PATH:=$(shell pwd)/../../freertos

AIR_SDK_PATH:=$(shell pwd)/../../air_system

AIR_SUPPORT_IGMP_SNP         = ENABLED
AIR_SUPPORT_IGMPV3_AWARE     = ENABLED
AIR_SUPPORT_IGMP_SNP_QUERIER = ENABLED
AIR_SUPPORT_IGMP_SNP_QUERIER_IGMPV3 = DISABLED
AIR_SUPPORT_PIM_AWARE        = ENABLED
AIR_SUPPORT_IGMP_SNP_SEARCH_MAC_TABLE = ENABLED
AIR_SUPPORT_LP               = ENABLED
AIR_SUPPORT_DHCP_SNOOP       = ENABLED
AIR_SUPPORT_ICMP_CLIENT      = ENABLED
AIR_SUPPORT_DEFAULT_CONFIG   = ENABLED
AIR_SUPPORT_VOICE_VLAN       = ENABLED
AIR_SUPPORT_SNMP             = ENABLED
AIR_SUPPORT_VOVLAN_SECURITY  = DISABLED
AIR_SUPPORT_IPV6             = ENABLED
AIR_SUPPORT_RSTP             = ENABLED
AIR_SUPPORT_POE              = DISABLED
AIR_SUPPORT_POE_WATCHDOG     = DISABLED
# MQTTD
AIR_SUPPORT_MQTTD            = ENABLED
AIR_SUPPORT_MQTTD_STARTONBOOT = ENABLED
AIR_SUPPORT_LLDPD            = ENABLED
AIR_SUPPORT_SFP              = ENABLED
AIR_SUPPORT_SFP_DDM          = ENABLED
